---
layout: page
location: pages/coding/lang/func/leaf
permalink: /pages/coding/lang/func/Dart-Bloc
---

## Testing blocs

### Verifying mocks in bloc tests

- Add a `verify` clause:

```dart
blocTest('Does a thing',
    build: () => MyBloc(),
    setUp: () {
        when(
            () => mockMyService.doThing(
                user.id!,
            ),
        ).thenAnswer((_) => Future.value());
    },
    act: (bloc) {
        bloc.add(Myevent(user: user,),);
    },
    expect: () => [
        const MyState(),
    ],
    verify: (_) {
        verify(
            () => mockMyService.doThing(
                user.id!,
            ),
        ).called(1);
    },
);
```

- More here on how to do it if you're not using the `blocTest` syntax: https://github.com/felangel/bloc/issues/157
    - In this case you'll use `expectLater` and `then`
    - There's an example of this kind of test [here](https://github.com/brianegan/flutter_architecture_samples/blob/41a033f6e67ec51bba2edf669cfcb857498db58c/frideos_library/test/stats_bloc_test.dart#L45), although it doesn't use the `then` syntax

### Troubleshooting "No method stub was called from within `when()`"

- Error when running test: "No method stub was called from within `when()`"
- This can happen if you accidentally used a real object instead of a mock object
- But it can also happen if there is a problem with your `when` clause
- It happened to me when I had the following code:

```dart
blocTest('Does a thing',
    build: () => MyBloc(),
    setUp: () {
        when(
            () => mockMyService.doThing(
                user.id!,
            ),
        ).thenAnswer((_) => Future.value());
    },
    act: (bloc) {
        bloc.add(Myevent(user: user,),);
    },
    expect: () => [
        const MyState(),
    ],
);
```

- The problem was that `user.id` was null, so it couldn't resolve `user.id!`
- I discovered this when I removed the `when` call altogether and just ran the code. In the code itself it was passing `user.id!` into `doThing`, and I got the error "Null check operator used on a null value"
- Presumably this error was also being generated by the bloc test code, but not being handled, so it just fell through to an error abhout problem,s with the `when` clause

## Troubleshooting

### Troubleshooting "Cannot add new events after calling close"

- We got this when we entered the same screen twice
- The error was thrown the second time we entered the screen, the first time the screen tried to fire an event for a bloc
- It turned out the problem was that we were using `GetIt.RegisterSingleton` instead of `GetIt.RegisterFactory` in `main.dart`
- We changed this...

```dart
  GetIt.I.registerSingleton<MatchboxBloc>(
    MatchboxBloc(),
  );
```

- ...to this:

```dart
  GetIt.I.registerFactory<MatchboxBloc>(
    () => MatchboxBloc(),
  );
```

- Relevant links:
    - Someone else with same problem: https://stackoverflow.com/a/78253377
    - Good explanation: https://github.com/felangel/bloc/issues/1734#issuecomment-694802121
